### ISSUE TITLE
Undefined symbols for architecture x86_64: "_clock_gettime"

### ISSUE THREAD

**Issue by ghenry** [rust-build/rust-build.action#91] opened 2024-02-24 21:02 UTC
Hi all,

This is my first time using this action and getting this for macos (Linux and Windows all good):

```
was built for newer macOS version (10.12) than being linked (10.8)
          Undefined symbols for architecture x86_64:
            "_clock_gettime", referenced from:
                std::sys::unix::time::Timespec::now::h0ebd2e38935918ca in libstd-4b3c9502f998a9c9.rlib(std-4b3c9502f998a9c9.std.ccb858c55971878c-cgu.0.rcgu.o)
            "_getentropy", referenced from:
                std::sys::unix::rand::hashmap_random_keys::ha92d0a2687c22b7a in libstd-4b3c9502f998a9c9.rlib(std-4b3c9502f998a9c9.std.ccb858c55971878c-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyone got any tips?

https://github.com/ghenry/CallSwitchOne-CLI/actions/runs/8030806698/job/21938587917

**Comment by jorgecarleitao** [comment] 2024-02-29 06:09
Duplicate of #88 and #86 .

**Closed** 2024-03-04 21:17 UTC
