### ISSUE TITLE
Docker v1.4.2 Does not Exist

### ISSUE THREAD

**Issue by akbog** [rust-build/rust-build.action#64] opened 2023-02-05 03:49 UTC
The docker version for the latest action release v1.4.2 does not exist / cannot be pulled. 

`Error: Pull down action image 'ghcr.io/rust-build/rust-build.action:v1.4.2'`

**Comment by denzyldick** [comment] 2023-02-05 18:16
I also encouter the same issue.

**Comment by Douile** [comment] 2023-02-07 15:09
Duplicate of #62

**Closed by Douile** 2023-02-07 15:09 UTC
